name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }}.${{ matrix.compiler }}.${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        compiler: [ 'g++-12', 'g++-11', 'clang-14', 'clang-13' ]
        build_type: [ 'Debug', 'Release' ]
    steps:
    - uses: actions/checkout@v3
    - name: Install software
      shell: bash
      run: |
        sudo apt install ${{ matrix.compiler }}
        sudo apt install libboost-all-dev
        sudo apt install cmake ninja-build
    - name: Configure CMake
      shell: bash
      run: |
        if [[ ${{ matrix.compiler }} =~ clang-([0-9]+) ]]
        then
          version=${BASH_REMATCH[1]}
          export CC=clang-$version
          export CXX=clang++-$version
        elif [[ ${{ matrix.compiler }} =~ g\+\+-([0-9]+) ]]
        then
          version=${BASH_REMATCH[1]}
          export CC=gcc-$version
          export CXX=g++-$version
        else
          echo "error: not valid compiler parameter."
          exit 1
        fi
        echo "CXX=$CXX"
        echo "CC=$CC"
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.build_type }}
